<template>
  <div class="work-container">
    <component v-bind:is="'style'" type="text/css">
      /* Stylesheet generated by Mechetle Mache */

      {{ styles }}
    </component>

    <div id="nav-wrapper">
      <Navigation disableTopOffset></Navigation>
    </div>

    <h1>
      {{ data?.title }}
    </h1>

    <div id="event-details">
      <p>
        {{ data?.location }}
      </p>

      <CommonDateDisplay
        :start-date="data?.startDate"
        :finish-date="data?.finishDate"
      />
    </div>
    <div
      v-if="data?.headerMedia.type == 'thumbnail' && !!data?.img"
      id="header-img"
    >
      <img :src="data.img || ''" />
    </div>

    <Container id="header-video-wrapper" v-if="data?.headerMedia.url">
      <div
        id="header-video"
        :class="{ video: data?.headerMedia.type != 'thumbnail' }"
      >
        <template v-if="data?.headerMedia.type == 'vimeo'">
          <iframe
            v-if="data.headerMedia.url"
            :src="data.headerMedia.url"
            width="640"
            height="360"
            frameborder="0"
            allow="autoplay; fullscreen; picture-in-picture"
            allowfullscreen
          ></iframe>
        </template>

        <template v-if="data?.headerMedia.type == 'youtube'">
          <iframe
            v-if="data.headerMedia.url"
            width="100%"
            height="100%"
            :src="data.headerMedia.url"
            title="YouTube video player"
            frameborder="0"
            allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
            referrerpolicy="strict-origin-when-cross-origin"
            allowfullscreen
          ></iframe>
        </template>
      </div>
    </Container>

    <div id="primary-details" v-if="data?.outboundLink?.url">
      <Container class="narrow">
        <a :href="data.outboundLink.url" class="button-outline">
          <span>
            <i
              :class="[
                'fa-brands',
                { 'fa-behance': data.outboundLink.url.includes('behance') },
              ]"
            ></i>

            <span>
              {{ data.outboundLink.label || "View" }}
            </span>
          </span>

          <span class="material-symbols-outlined"> arrow_right_alt </span>
        </a>
      </Container>
    </div>

    <div id="callout-description">
      <Container class="narrow">
        <p class="h6 multiline-text">
          {{ data?.callout }}
        </p>
      </Container>
      <Container class="fluid" v-if="data?.desc && data?.desc != ''">
        <div id="desc" v-html="descriptionBody"></div>
      </Container>
    </div>

    <MacheGroup
      v-if="data && data.body"
      v-model:block="data.body.children"
      :path="-1"
    >
    </MacheGroup>
  </div>
</template>

<script setup lang="ts">
import { marked } from "marked";

onMounted(() => {
  window.scrollTo(0, 0);
});

const route = useRoute();

const { data } = await useFetch(`/api/events/${route.params.event}`, {});

useHead({
  title: ` | ${data.value?.title}`,
  meta: [
    {
      name: "description",
      content: `${data.value?.callout}`,
    },
    {
      name: "og:image",
      content: `${data.value?.img}`,
    },
    {
      name: "twitter:card",
      content: "summary_large_image",
    },
  ],
});

console.log({ img: data.value?.img });

const descriptionBody = computed(() => {
  if (!data.value?.desc) return "";

  // Process any markdown in the description
  console.log(
    "Processing markdown for description",
    marked.parse(data.value.desc)
  );
  return marked.parse(data.value.desc);
});

const styles = computed(() => {
  let generatedStyles = "";

  for (let key in data.value?.style) {
    let props = "";

    let selectorStyle = data.value?.style[key];
    for (let prop in selectorStyle) {
      props =
        props +
        `${prop.replace(
          /[A-Z]+(?![a-z])|[A-Z]/g,
          ($, ofs) => (ofs ? "-" : "") + $.toLowerCase()
        )}: ${
          typeof selectorStyle[prop] == "string" &&
          selectorStyle[prop].length > 0
            ? selectorStyle[prop]
            : selectorStyle[prop].length > 0 // else if it's an array
            ? //@ts-ignore
              selectorStyle[prop].join(" ")
            : "initial"
        }`;
      props = props + ";";
    }

    generatedStyles = generatedStyles + ` #${key} {${props}}`;
  }

  console.log(generatedStyles);
  return generatedStyles;
});
</script>

<style lang="scss" scoped>
@use "sass:map";

#desc {
  margin-top: 10vh;
  text-align: left;
}

#nav-wrapper {
  padding: 2em 0;
}

#header-img {
  width: 100%;
  max-width: 1200px;
  margin: auto;
  margin-bottom: 6em;

  img {
    width: 100%;
  }
}

#header-video-wrapper {
  animation-name: headerScrollAnimation;
  animation-timing-function: cubic-bezier(0.64, 0.01, 0.16, 0.99);
  animation-duration: 1ms;
  animation-timeline: --scrollTimeline;
  animation-range: contain 0% contain 100%;
  margin-bottom: 6em;

  @media screen and (max-width: map.get($breakpoint, "medium")) {
    max-width: 1200px;
  }

  @media screen and (min-width: map.get($breakpoint, "large")) {
    max-width: 80vw;
  }
}

#header-video {
  aspect-ratio: 16 / 9;
  background: #de9797;
  border-radius: 30px;
  position: relative;
  overflow: clip;

  iframe {
    height: 100%;
    width: 100%;
  }

  &.video {
    background: #000;
  }
}

.work-container {
  padding: 0 1.5em;
  padding-bottom: 40vh;

  @media screen and (max-width: map.get($breakpoint, "medium")) {
    margin-top: 12em;
  }

  h1 {
    text-align: center;
    view-transition-name: selected-post-heading;
  }

  #callout-description {
    text-align: center;
  }
}

#primary-details {
  margin-bottom: 4em;
  padding: 0 1.5em;

  .grid-container.narrow {
    max-width: 580px;
  }
}

.multiline-text {
  white-space: pre-line;
}

#event-details {
  margin: 0.5em auto 3em;
  max-width: 300px;
  width: 100%;
  font-weight: 500;

  > p {
    text-align: center;
  }
}
</style>
